image: ruby

stages:
  - test_specs
  - test_units

primary:
  services:
    - postgres
  stage: .pre

spec_task:
  stage: test_specs
  before_script: bundle install
  script: bundle exec rspec spec/*.rb

unit_task:
  stage: test_units
  before_script: bundle install
  script: bundle exec ruby test/*.rb