image: ruby

stages:
  - test_units
  - test_specs


unit_task:
  stage: test_units
  before_script:
    - bundle install
  script:
    - bundle exec ruby test/*.rb

spec_task:
  stage: test_specs
  before_script:
  - bundle install
  script:
  - bundle exec rspec spec/*.rb